stages:
    - build
    
before_script:
    - "ls"
    - "dotnet restore"

build:
    stage: build
    only:
        - schedules
    script:
        - "dotnet publish -c Release -o /opt/WorkFlowAPI/DotnetPublish/"
        - "systemctl stop supervisord"
        - "rm -rf /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "mv /opt/WorkFlowAPI/dotnetcore_modules /opt/WorkFlowAPI/dotnetcore_modules_backup"
        - "mkdir /opt/WorkFlowAPI/dotnetcore_modules" 
        - "cp -a /opt/WorkFlowAPI/DotnetPublish/. /opt/WorkFlowAPI/dotnetcore_modules/"
        - "systemctl start supervisord"
        - "rm -rf /opt/WorkFlowAPI/DotnetPublish"


